### ISSUE TITLE
How to add admin users after enabling Google Authentication

### ISSUE THREAD

**Issue by rezuma** [jupyterhub/the-littlest-jupyterhub#508]
Hello,

I have enable Oauth authentication, users can know login into the server using their Google Account.

Is there a way to restrict which user can login? Currently everyone with a Google Account can access the server.
Once I enabled Google, I can no longer access with the first admin account. I have tried  tljh-config add-item users.admin for an existing google account but his account still doesnt show the capability of create other admins

thannks
Ramon

**Comment by Gilles-Synbiosys** [comment]
Hello, 

This worked for me :    
```yaml
hub:
 config:
   GoogleOAuthenticator:
      client_id: **********************
      client_secret: **************************************
      oauth_callback_url: http://*********************/hub/oauth_callback
      hosted_domain:
        - ***********
        - ************
      login_service: **********************
    JupyterHub:
      authenticator_class: google
      admin_users:
        - user1@gmail.com
        - user2@gmail.com
```
