### ISSUE TITLE
Using a custom traefik toml file or template

### ISSUE THREAD

**Issue by hMED22** [jupyterhub/the-littlest-jupyterhub#543]
I'm trying with @jhadjar to change the proxy config in `/opt/tljh/state/traefik.toml` but it is overwritten by [traefik.toml.tpl ]( https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/tljh/traefik.toml.tpl ) every time the proxy is reloaded, is there any way to set a custom file or template to be used instead?

**Comment by mskblackbelt** [comment]
Seconded. I'm currently restoring from a backup file each time, but it doesn't seem like the process should be that difficult. Alternately, is there a (supported) way to place some configuration values in `jupyterhub_config.d` to have some data appended to the existing TOML file?

**Comment by jhadjar** [comment]
Adding more context to @hMED22's issue. The problem lies in https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/tljh/traefik.py#L90

```python
def ensure_traefik_config(state_dir):
    """Render the traefik.toml config file"""
    config = load_config()
    config['traefik_api']['basic_auth'] = compute_basic_auth(
        config['traefik_api']['username'],
        config['traefik_api']['password'],
    )

    with open(os.path.join(os.path.dirname(__file__), "traefik.toml.tpl")) as f:
        template = Template(f.read())
```

The problematic line gives no way to pass the template programmatically:

```python
    with open(os.path.join(os.path.dirname(__file__), "traefik.toml.tpl")) as f:
```

**Comment by GeorgianaElena** [comment]
Indeed, `traefik.toml.tpl` is meant to be modified through `tljh-config` (to the extent of an option being configurable at all).

Can you please explain a bit what's your use-case and how would modifying `traefik.toml.tpl` help?

Some of the config in traefik.toml has to be there for TLJH and traefik-proxy to be functional. However, I think it is possible to add an *escape hatch* to extend the `traefik.toml` template, similarly with how we do for the `juptyerhub_config.py.`
WDYT about this @yuvipanda?

**Comment by mskblackbelt** [comment]
I'm trying to set the `rules.toml` file to look like so:

```toml
[frontends]
  [frontends.default]
  backend = "backend__2F"
  passHostHeader = true
  priority = 80
    [frontends.default.routes.test]
    rule = "Path:/;AddPrefix:/hub"
    data = "{\"hub\": true}"

  [frontends.frontend__2F]
  backend = "backend__2F"
  passHostHeader = true
  priority = 90
    [frontends.frontend__2F.routes.rule1]
    # rule = "PathPrefix:/hub"
    rule = "Host: jupyter.example.com"

  [frontends.webmo]
  backend = "webmo"
  passHostHeader = true
  priority = 100
    [frontends.webmo.routes.rule1]
    # rule = "PathPrefix:/webmo"
    rule = "Host: webmo.example.com"

[backends]
  [backends.backend__2F]
    [backends.backend__2F.servers.server1]
    url = "http://127.0.0.1:15001"

  [backends.webmo]
    [backends.webmo.servers.server1]
    url = "http://webmo.example.com:8080"
```

I'd like to pass all addresses at `jupyter.example.com` to TLJH and everything at `webmo.example.com` to Apache which is hosting a WebMO installation. With this `rules.toml` file, it works, but TLJH (or Traefik?) periodically overwrites the file, breaking the Apache proxy. 

I believe these rules (at least the WebMO ones) could be placed in the Traefik template file, but I'd like to try to keep within the `tljh-config` framework as much as possible.
