### ISSUE TITLE
BUG?: TLJH OAuth redirecting to "GitLab.Com" URL rather than my own "GitLab-CE" URL as instructed ...

### ISSUE THREAD

**Issue by nmvega** [jupyterhub/the-littlest-jupyterhub#548]
Hello Friends:

I have `GitLab CE` installed and use it as the `Oauth` authentication mechanism for my various `JupyterHub` builds: `SystemdSpawner`, `DockerSpawner`, etc. It works well.

However, for my new `TLJH` installation, when I click on `Sign in with GitLab`, the redirect takes me to the `GitLab.com` URL rather than my own `GitLab CE` URL (shown below). I pasted my redacted `config.yaml` file below.

This is odd. I've tried everything I can think of with not luck. I'm using the latest copy of `TLJH`, downloaded today.

Any ideas and help? Thank you in advance!

```
users:
  admin:
  - jdoe
https:
  enabled: true
  port: 8443
  letsencrypt:
    email: jdoe@example.com
    domains:
    - jupyterhub.k8sbox.io
  tls:
    key: /etc/jupyter.d/conf.d/ssl.d/jupyterhub.key
    cert: /etc/jupyter.d/conf.d/ssl.d/jupyterhub.crt
http:
  port: 80
limits:
  memory: 4G
  cpu: 12
user_environment:
  default_app: jupyterlab
auth:
  GitLabOAuthenticator:
    client_id: XXXXXXXXXXXXXXXXXXXXXXXXXX
    client_secret: YYYYYYYYYYYYYYYYYYYYYYYYYY
    oauth_callback_url: https://jupyterhub.k8sbox.io:8443/hub/oauth_callback
    server_address: https://gitlab.k8sbox.io:443
  type: oauthenticator.gitlab.GitLabOAuthenticator
```
