### ISSUE TITLE
Extra TOML files aren't working in configuration

### ISSUE THREAD

**Issue by mskblackbelt** [jupyterhub/the-littlest-jupyterhub#583]
### Bug description

After updating my installation of TLJH, the new `traefik_config.d` directory appears. I placed a TOML file containing my desired configuration into the folder, `state/traefik.toml` incorporates the contents, but routing to the second site doesn't work (all requests are sent to JupyterHub). 

#### Expected behaviour

I expected the contents of `rules.toml` to reflect the new settings included in my custom TOML file in the `traefik_config.d` directory. When navigating to [webmo.example.com][webmo], I expect the browser to negotiate an https connection; then the login page for [WebMO](www.webmo.net) should pull up. 

#### Actual behaviour

The contents of `rules.toml` don't included any of the content from my custom TOML file. When I navigate to [webmo.example.com][webmo], the request is redirected to [https://webmo.hcpchemlab.org/hub/login](https://webmo.hcpchemlab.org/hub/login), a login page for JupyerHub. When I navigate to [webmo.example.com:8080](webmo.example.com:8080), the login page appears, but the https connection isn't created.

### How to reproduce

Here are the contents of my custom TOML file:

```toml
[frontends]
  [frontends.jupyterhub]
  backend = "jupyterhub"
  passHostHeader = true
  priority = 90
    [frontends.jupyterhub.routes.rule1]
    rule = "Host: jupyter.example.com"

  [frontends.webmo]
  backend = "webmo"
  passHostHeader = true
  priority = 100
    [frontends.webmo.routes.rule1]
    rule = "Host: webmo.example.com"

[backends]
  [backends.backend__2F]
    [backends.backend__2F.servers.server1]
    url = "http://127.0.0.1:15001"
  
  [backends.jupyterhub]
    [backends.jupyterhub.servers.server1]
    url = "http://127.0.0.1:15001"

  [backends.webmo]
    [backends.webmo.servers.server1]
    url = "http://127.0.0.1:8080"
```
1. I place this file in `traefik_config.d` and run `tljh-config reload proxy`.
2. The contents of this file are incorporated into `state/traefik.toml`, but URL redirection doesn't seem to work. 
3. When I navigate to [webmo.example.com][webmo], I'm redirected to [https://webmo.hcpchemlab.org/hub/login](https://webmo.hcpchemlab.org/hub/login). 
4. If I navigate to [webmo.hcpchemlab.org:8080](webmo.hcpchemlab.org:8080), I can get to the WebMO login page, but it is unsecured. 

If I replace `rules.toml` with the contents of the custom TOML file, navigation to [webmo.example.com][webmo] redirects to https and pulls up the WebMO site. 

### Your personal set up

This installation exists on a Google Cloud server.

 - OS: Ubuntu
 
 - Version: 18.04
 
 - Configuration: JupyterHub 1.0.0, standard WebMO installation, version 19.0.009, hosted on port 8080 via Apache2
 

[webmo]: webmo.example.com
[jupyter]: jupyter.example.com

**Comment by GeorgianaElena** [comment]
Hey @mskblackbelt :wave: Thanks for reporting this issue.

>After updating my installation of TLJH, the new traefik_config.d directory appears. I placed a TOML file containing my desired configuration into the folder, state/traefik.toml incorporates the contents, but routing to the second site doesn't work (all requests are sent to JupyterHub).

The reason why the routing doesn't work, is because Traefik is configured through:
```toml
[file]
filename = "rules.toml"
watch = true
```
to read its [*dynamic* config](https://docs.traefik.io/v1.7/basics/#dynamic-traefik-configuration) from `rules.toml` and only its  [*static* configuration](https://docs.traefik.io/v1.7/basics/#static-traefik-configuration) is supposed to be in `traefik.toml`.

Traefik also supports having both static and dynamic config in the same file, but in Traefik-Proxy, we decided that it's better to have them separated. Because because `traefik.toml` can now be extended, one could potentially change this behavior and configure Traefik to read its configuration (static + dynamic) from the same file, but this will break Traefik-Proxy, which assumes that they are separated and this in turn, will break JupyterHub.

So, for your use-case to work, we will need to find a way of extending `rules.toml`.
I believe there are two ways to achieve this:
* Open `rules.toml` in append mode here:
https://github.com/jupyterhub/the-littlest-jupyterhub/blob/6cbc997ed80969374cee56b80eb515ae2355b9cc/tljh/traefik.py#L134-L135
This way one could place some extra rules in the file that won't get overwritten when reloading. (Traefik-Proxy should be able to load some pre-existing config from `rules.toml`)
* Have Traefik [watch for rules in a directory](https://docs.traefik.io/v1.7/configuration/backends/file/#multiple-separated-files) instead of just `rules.toml`

@yuvipanda, what do you think about exposing a mechanism to extend `rules.toml` in TLJH (maybe using one of the above options)?
