### ISSUE TITLE
Azure AD signin with TLJH doesn't work - tljh config ignored

### ISSUE THREAD

**Issue by tamasSzentandrasi** [jupyterhub/the-littlest-jupyterhub#609]
### Bug description

azuread.py doesn't seem to parse in any of the configuration details included in the tljh config.

#### Expected behaviour

I'm using the following [TLJH](https://github.com/jupyterhub/the-littlest-jupyterhub) config, with the substitutions of <> with the appropriate content:

```
spec:
  env:
    name: AAD_TENANT_ID
    value: <valid Azure AD Tenant ID>
auth:
  type: azuread
  azuread:
    client_id: <client_id>
    client_secret: <client_secret>
    callback_url: https://<ourdomain>/hub/callback
    tenant_id: <same valid Azure AD Tenant ID>
cert_reqs: CERT_REQUIRED
```

since it references azuread, and it does call azuread.py (since the site correctly shows "Sign in with Azure AD"), it should be able to get the configuration details to construct a valid  redirect url to access jupyterhub. 

#### Actual behaviour

The redirect url has the following structure:

`https://login.microsoftonline.com/<tenant-id>/oauth2/authorize?response_type=code&redirect_uri=<ourdomain>%2Fhub%2Foauth_callback&client_id=&state=<long string of randomness>`

As you can see, it failed to include the client_id, and thus the redirect url does not work.

### How to reproduce

Using valid Azure AD configuration details on a [TLJH](https://github.com/jupyterhub/the-littlest-jupyterhub) installation, set the tljh-config to the appropriate form (similar with mine, only substituting in your configuration).
Reload the tljh-config, and try to sign in.

### Your personal set up

AWS Linux 18.04
