### ISSUE TITLE
Support needed for Oathenticator's Azure AD signin with TLJH

### ISSUE THREAD

**Issue by tamasSzentandrasi** [jupyterhub/the-littlest-jupyterhub#610]
### Proposed change

Currently, [Oauthenticator](https://github.com/jupyterhub/oauthenticator) uses [azuread.py](https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/azuread.py) to handle the cases where tljh-config contains azuread as the auth type. It seems to primarily use environmental variables to get the required details for the construction of a valid redirect url. However, simply by making sure the only referenced 'AAD_TENANT_ID' is valid, it fails to include other necessary configuration details, that have been given in the tljh config below. 

The contents of tljh-config (reload was successful - active):

```
spec:
  env:
    name: AAD_TENANT_ID
    value: <valid Azure AD Tenant ID>
auth:
  type: azuread
  azuread:
    client_id: <client_id>
    client_secret: <client_secret>
    callback_url: https://<ourdomain>/hub/callback
    tenant_id: <same valid Azure AD Tenant ID>
cert_reqs: CERT_REQUIRED
```

I've already submitted a [Bug report](https://github.com/jupyterhub/oauthenticator/issues/365) on the Oauthenticator side, However the issue is between TLJH and [Oauthenticator](https://github.com/jupyterhub/oauthenticator), and thus the solution has to be some sort of support from both sides to allow this use-case for authentication.
