### ISSUE TITLE
Python environment is different in notebook and in terminal

### ISSUE THREAD

**Issue by PaleNeutron** [jupyterhub/the-littlest-jupyterhub#626]
### Bug description

After installing, I found python in notebook is:
```
import sys
print(sys.path)

['/home/jupyter-john',
 '/opt/tljh/user/lib/python37.zip',
 '/opt/tljh/user/lib/python3.7',
 '/opt/tljh/user/lib/python3.7/lib-dynload',
 '',
 '/opt/tljh/user/lib/python3.7/site-packages',
 '/opt/tljh/user/lib/python3.7/site-packages/IPython/extensions',
 '/home/jupyter-john/.ipython']
```

while the default python in terminal is:

```
jupyter-john@klfy-Z10PE-D8-WS:~$ which python
/opt/anaconda3/bin/python
```
Is there some config wrong? How can I fix that.

#### Expected behaviour

notebook and terminal use same python

#### Actual behaviour

notebook use tljh python and terminal use conda python

### How to reproduce

I'm not sure, I just install it using bootstrap.py.

### Your personal set up

```
sudo tljh-config show
users:
  admin:
  - john
auth:
  type: nativeauthenticator.NativeAuthenticator
  NativeAuthenticator:
    open_signup: true
  FirstUseAuthenticator:
    create_users: true
```
