### ISSUE TITLE
tljh not using custom templates

### ISSUE THREAD

**Issue by astroDimitrios** [jupyterhub/the-littlest-jupyterhub#653]
I am trying to get my tljh install to use custom html templates but nothing I do seems to work.
The docs for tljh don't mention how to customise the templates or show what the output of `sudo tljh-config show` should be.
I read on a Google group that the default files are in /opt/tljh/hub/share/jupyterhub/templates/ but I don't have permission to edit them even though I'm admin.

**Could the docs be updated to clarify how to use your own templates or modify existing ones?**

I set up tljh on a google cloud vm following the instructions on the docs.
I then copied the templates and static directories into /home/jupyterhub-astrodth/ (astrodth is the admin user).
Then I run:
`sudo tljh-config set c.JupyterHub.template_paths '/home/jupyter-astrodth/templates/'`
If I run `sudo tljh-config show` again I get:

```
users:
  admin:
  - astrodth
user_environment:
  default_app: jupyterlab
c:
  JupyterHub:
    template_paths: /home/jupyter-astrodth/templates/
```

After reloading the config using `sudo tljh-config reload` it doesn't seem to be pointing to my modified templates.
Are there other steps I'm missing? Is that the correct way to set the template paths?
