### ISSUE TITLE
[GitHub] Config option `allowed_organizations` is not working

### ISSUE THREAD

**Issue by saurabh-glam** [jupyterhub/the-littlest-jupyterhub#808]
### Bug description
This is my `/opt/tljh/config/config.yaml` file:
```
users:
  admin:
  - abc
  - abc
auth:
  type: oauthenticator.github.GitHubOAuthenticator
  GoogleOAuthenticator:
    client_id: ---
    client_secret: ---
    oauth_callback_url: ---
  FirstUseAuthenticator:
    create_users: true
  GitHubOAuthenticator:
    client_id: ---
    client_secret: ---
    oauth_callback_url: ---
    allowed_organizations:
      - my_org_name
    scope:
      - read:user
services:
  cull:
    timeout: 600000
```

#### Expected behaviour

While signing in via GitHub, if the org is not `my_org_name` then it shouldn't login.

#### Actual behaviour

While signing in via GitHub, if the org is not `my_org_name` then it is logging in.

### How to reproduce

1. Go to server and update the config file by adding `allowed_organizations: ...` and reload using `sudo tljh-config reload`
2. Click to your hub url, signin with GitHub (from an account which is not a part of organization mentioned in tljh-config)
3. Authorise and It will login :(

### Your personal set up

using a distribution of the-littlest-jupyterhub.

ubuntu 20.04
cloud: AWS 
instance type: t3.large

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
c.GitHubOAuthenticator.allowed_organizations = ['my_org_name']
```
</details>
