### ISSUE TITLE
Collect notebooks from students

### ISSUE THREAD

**Issue by jrasero** [jupyterhub/the-littlest-jupyterhub#844]
Hi,

I've set up a jupyterhub distribution for my class using this littlest jupyterhub option. Everything works great, so thanks a lot for having developed such an amazing project. 

I have also been able to distribute different notebooks with my students using the nbgitpuller option and it all worked like a charm, so again, thanks a lot for this, as it's really easy to do.

Now, the question and doubt that came to my mind is how to collect these notebooks that I distributed from them. Say I distributed them a notebook vía nbgitpuller as I said above, then the students do some work on It and I want to evaluate this work. What's the best for them to send me back these notebooks?

I am on the process of trying to incorporate nbgrader to jupyterhub, which will simplify things a lot, but in the meantime I would need to have an option for them to send me their work if needed.

Any help will be really much appreciated!!

**Comment by westurner** [comment]
- https://github.com/quobit/awesome-python-in-education#jupyter
  - https://github.com/jupyterhub/jupyterhub-deploy-teaching demos nbgrader config:
    - https://github.com/jupyterhub/jupyterhub-deploy-teaching/issues/106
    - https://github.com/jupyterhub/jupyterhub-deploy-teaching/blob/63c89099880653f1ad97025dd9e652ea102602b1/group_vars/jupyterhub_hosts#L49-L54
      ```
      # ---------------------------------------------------
      # Nbgrader config directories
      # ---------------------------------------------------
      
      
      nbgrader_log_dir: /var/log/nbgrader
      nbgrader_exchange_dir: /srv/nbgrader/exchange
      ```
     - https://github.com/jupyterhub/jupyterhub-deploy-teaching/blob/63c89099880653f1ad97025dd9e652ea102602b1/host_vars/hostname.example#L193-L202
       ```
        # ------------------------------------------------------------------------------
        # nbgrader
        # ------------------------------------------------------------------------------
        
        
        # nbgrader is a system for assigning, collecting and grading notebook based
        # homework assignments. For more details see:
        # http://nbgrader.readthedocs.io/en/stable/
        
        
        # Set to `true` to enable.
        use_nbgrader: false
        ```
  
      - https://github.com/jupyterhub/jupyterhub-deploy-teaching/blob/63c89099880653f1ad97025dd9e652ea102602b1/deploy.yml#L42-L43
        ```
            - role: nbgrader
              when: use_nbgrader is defined and use_nbgrader
        ```
        
      - https://github.com/jupyterhub/jupyterhub-deploy-teaching/blob/63c89099880653f1ad97025dd9e652ea102602b1/roles/nbgrader/tasks/main.yml#L1-L33
        ```yaml
        ---
        
        - name: pip install nbgrader
          pip: name={{item}} state=present executable=pip
          become: true
          with_items:
            - nbgrader
        
        - name: make sure /var/log/nbgrader exists
          file: path={{nbgrader_log_dir}}/ state={{item}} owner=root group=root mode=0755
          become: true
          with_items:
            - directory
            - touch
        
        - name: make sure /srv/nbgrader/exchange exists
          file: path={{nbgrader_exchange_dir}}/ state={{item}} owner=root group=root mode=0777
          become: true
          with_items:
            - directory
            - touch
        
        - name: install the nbgrader nbextensions
          command: jupyter nbextension {{item}} --sys-prefix --py nbgrader
          become: true
          with_items:
            - install
            - enable
        
        - name: install the nbgrader serverextension
          command: jupyter serverextension enable --sys-prefix --py nbgrader
          become: true
        
        ```
