### ISSUE TITLE
Jupyter nbextensions: jsonschema 3.2.0 has no such extra feature 'format-nongpl'

### ISSUE THREAD

**Issue by aretaon** [jupyterhub/the-littlest-jupyterhub#845]
### Bug description

Installing jupyter nbextensions as described at https://tljh.jupyter.org/en/latest/howto/admin/enable-extensions.html does not work.
An issue regarding the jsonschema is raised.

#### Expected behaviour

`sudo -E jupyter contrib nbextension install --sys-prefix` returns message of successfull install of nbextensions.

#### Actual behaviour

The command returns `pkg_resources.UnknownExtra: jsonschema 3.2.0 has no such extra feature 'format-nongpl'`.
Accordingly, `sudo -E pip install jsonschema[format-nonpl]` returns `WARNING: jsonschema 3.2.0 does not provide the extra 'format-nongpl'`.
However, `sudo -E pip install jsonschema[format_nonpl]` (with underscore) works. 

### How to reproduce

  - Fresh tljh install
  - `sudo -E pip install jupyter_contrib_nbextensions`
  - `sudo -E jupyter contrib nbextension install --sys-prefix`

### Personal set up

 - OS:
 Ubuntu 22.04.1
 - Version(s):
Python 3.10.6
pip 22.0.2

<details><summary>Full environment</summary>

```
anyio==3.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.2.1
attrs==21.2.0
Automat==20.2.0
Babel==2.8.0
backcall==0.2.0
bcrypt==3.2.0
beautifulsoup4==4.11.1
bleach==6.0.0
blinker==1.4
certifi==2020.6.20
cffi==1.15.1
chardet==4.0.0
click==8.0.3
cloud-init==22.4.2
colorama==0.4.4
comm==0.1.2
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==3.4.8
dbus-python==1.2.18
debugpy==1.6.6
decorator==5.1.1
defusedxml==0.7.1
distro==1.7.0
distro-info===1.1build1
entrypoints==0.4
executing==1.2.0
fastjsonschema==2.16.2
greenlet==1.1.2
httplib2==0.20.2
hyperlink==21.0.0
idna==3.3
importlib-metadata==4.6.4
incremental==21.3.0
ipykernel==6.20.2
ipython==8.8.0
ipython-genutils==0.2.0
jedi==0.18.2
jeepney==0.7.1
Jinja2==3.0.3
jsonpatch==1.32
jsonpointer==2.0
jsonschema==3.2.0
jupyter-contrib-core==0.4.2
jupyter-contrib-nbextensions==0.7.0
jupyter-events==0.6.3
jupyter-highlight-selected-word==0.2.0
jupyter-nbextensions-configurator==0.6.1
jupyter_client==7.4.9
jupyter_core==5.1.5
jupyter_server==2.1.0
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
keyring==23.5.0
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lxml==4.9.2
MarkupSafe==2.0.1
matplotlib-inline==0.1.6
mistune==2.0.4
more-itertools==8.10.0
msgpack==1.0.3
nbclassic==0.4.8
nbclient==0.7.2
nbconvert==7.2.9
nbformat==5.7.3
nest-asyncio==1.5.6
netifaces==0.11.0
notebook==6.5.2
notebook_shim==0.2.2
oauthlib==3.2.0
packaging==23.0
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
platformdirs==2.6.2
prometheus-client==0.16.0
prompt-toolkit==3.0.36
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.4.8
pyasn1-modules==0.2.1
pycparser==2.21
Pygments==2.14.0
PyGObject==3.42.1
PyHamcrest==2.0.2
PyJWT==2.3.0
pynvim==0.4.2
pyOpenSSL==21.0.0
pyparsing==2.4.7
pyrsistent==0.18.1
pyserial==3.5
python-apt==2.4.0
python-dateutil==2.8.2
python-debian===0.1.43ubuntu1
python-json-logger==2.0.4
python-magic==0.4.24
pytz==2022.1
PyYAML==5.4.1
pyzmq==25.0.0
requests==2.25.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
SecretStorage==3.3.1
Send2Trash==1.8.0
service-identity==18.1.0
six==1.16.0
sniffio==1.3.0
sos==4.4
soupsieve==2.3.2.post1
ssh-import-id==5.11
stack-data==0.6.2
systemd-python==234
terminado==0.17.1
tinycss2==1.2.1
tornado==6.2
traitlets==5.8.1
Twisted==22.1.0
ubuntu-advantage-tools==27.12
ubuntu-drivers-common==0.0.0
ufw==0.36.1
unattended-upgrades==0.1
urllib3==1.26.5
wadllib==1.3.6
wcwidth==0.2.6
webcolors==1.12
webencodings==0.5.1
websocket-client==1.4.2
xkit==0.0.0
zipp==1.0.0
zope.interface==5.4.0
```
</details>

<details><summary>Configuration</summary>

```
https:
  enabled: true
  tls:
    key: /etc/certs/KEY.key
    cert: /etc/certs/CERT.cert
auth:
  LDAPAuthenticator:
    server_address: SERVER
    use_ssl: true
    user_search_base: ou=accounts,o=ORG
    lookup_dn_search_user: None
    lookup_dn_search_password: None
    lookup_dn: false
    bind_dn_template: cn={username},ou=accounts,o=ORG
    search_filter: (&(cn={username})(groupMembership=cn=GROUP,ou=groups,o=ORG))
  type: ldapauthenticator.LDAPAuthenticator
log_level: INFO
users:
  admin:
  - ADMIN
```
</details>
