### ISSUE TITLE
On restart Jupyterhub Container user list is not coming

### ISSUE THREAD

**Issue by Anup-Zessta** [jupyterhub/the-littlest-jupyterhub#934]
I configured the container by attaching a named volume to the **"/home"** directory and created users. Following this, I stopped the container. Upon subsequent container instantiation, the preserved volume facilitated the restoration of user-related data to the **"/home"** directory. Consequently, the files generated under the admin were successfully retrieved; however, the listing of users within the admin was absent. **Is there a method to recover the user account listing?** Furthermore, upon manually generating a user through the admin and subsequently logging into that account, the files created in that specific user account were accessible.
**I am proving my docker-compose file**
```
version: '3'
services:
  tljh-dev:
    build:
      context: .
      dockerfile: integration-tests/Dockerfile
    privileged: true
    ports:
      - "60020:80"
    volumes:
      - "./:/srv/src"
      - data-volume:/home
   
volumes:
  data-volume:
```
